/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonVariant } from "./components/ui/erix-button/erix-button.types";
import { DividerOrientation, DividerSize } from "./components/ui/erix-divider/erix-divider";
import { DropdownPosition } from "./components/ui/erix-dropdown/erix-dropdown";
import { EditorConfig, ErixEditorAPI, ErixPluginConfig, ToolbarItem } from "./api/index";
import { IconName } from "./components/ui/erix-icon/icons";
import { PopoverPlacement } from "./components/ui/erix-popover/erix-popover";
import { SelectOption, SelectWidth } from "./components/ui/erix-select/erix-select";
import { EditorView } from "prosemirror-view";
export { ButtonSize, ButtonVariant } from "./components/ui/erix-button/erix-button.types";
export { DividerOrientation, DividerSize } from "./components/ui/erix-divider/erix-divider";
export { DropdownPosition } from "./components/ui/erix-dropdown/erix-dropdown";
export { EditorConfig, ErixEditorAPI, ErixPluginConfig, ToolbarItem } from "./api/index";
export { IconName } from "./components/ui/erix-icon/icons";
export { PopoverPlacement } from "./components/ui/erix-popover/erix-popover";
export { SelectOption, SelectWidth } from "./components/ui/erix-select/erix-select";
export { EditorView } from "prosemirror-view";
export namespace Components {
    /**
     * @component ErixButton
     * A reusable button component for the editor toolbar and UI.
     */
    interface ErixButton {
        /**
          * Whether the button is in an active/pressed state
          * @default false
         */
        "active": boolean;
        /**
          * Tooltip text for the button
          * @default ''
         */
        "buttonTitle": string;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * The size of the button
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * The visual style variant of the button
          * @default 'default'
         */
        "variant": ButtonVariant;
    }
    /**
     * @component ErixDivider
     * A visual separator for toolbar groups and sections.
     */
    interface ErixDivider {
        /**
          * The orientation of the divider
          * @default 'vertical'
         */
        "orientation": DividerOrientation;
        /**
          * The size of the divider
          * @default 'md'
         */
        "size": DividerSize;
    }
    /**
     * @component ErixDropdown
     * A reusable dropdown component for the editor toolbar.
     * Provides a trigger button and a menu that opens on click.
     */
    interface ErixDropdown {
        /**
          * Whether to use extended menu style (for text-based options)
          * @default false
         */
        "extended": boolean;
        /**
          * Whether the dropdown menu is currently open
          * @default false
         */
        "open": boolean;
        /**
          * Position of the dropdown menu relative to the trigger
          * @default 'left'
         */
        "position": DropdownPosition;
        /**
          * Whether the trigger should show active state when open
          * @default true
         */
        "showActiveState": boolean;
        /**
          * Tooltip text for the trigger button
          * @default ''
         */
        "triggerTitle": string;
    }
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar and plugin system.
     */
    interface ErixEditor {
        "config"?: EditorConfig;
        "content"?: string;
        /**
          * @default 'Arial, sans-serif'
         */
        "defaultFontFamily": string;
        /**
          * @default '12pt'
         */
        "defaultFontSize": string;
        "disabledPlugins"?: string[];
        "getAPI": () => Promise<ErixEditorAPI>;
        /**
          * @default 'Start typing...'
         */
        "placeholder": string;
        "plugins"?: ErixPluginConfig[];
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 'light'
         */
        "theme": 'light' | 'dark' | string;
    }
    interface ErixIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size": number;
    }
    /**
     * @component ErixPopover
     * A smart popover component with auto-positioning.
     * Appends content to body for proper positioning.
     * Automatically flips position when there's not enough space.
     */
    interface ErixPopover {
        /**
          * Anchor element or bounding rect to position relative to
         */
        "anchorRect"?: DOMRect;
        /**
          * Whether to auto-flip when there's not enough space
          * @default true
         */
        "autoFlip": boolean;
        /**
          * Close the popover
         */
        "hide": () => Promise<void>;
        /**
          * Offset distance from the trigger (in pixels)
          * @default 8
         */
        "offset": number;
        /**
          * Whether the popover is visible
          * @default false
         */
        "open": boolean;
        /**
          * Preferred placement of the popover
          * @default 'top'
         */
        "placement": PopoverPlacement;
        /**
          * Open the popover at a specific anchor rect
         */
        "show": (anchorRect?: DOMRect) => Promise<void>;
        /**
          * Manually trigger a position update
         */
        "updatePosition": () => Promise<void>;
    }
    /**
     * @component ErixSelect
     * A reusable select/dropdown component for the editor toolbar.
     */
    interface ErixSelect {
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Icon-only mode - displays only an icon in the trigger (for compact toolbars)
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Array of options for the select
          * @default []
         */
        "options": SelectOption[];
        /**
          * Tooltip text for the select
          * @default ''
         */
        "selectTitle": string;
        /**
          * Icon name to display in the trigger (used with iconOnly mode)
         */
        "triggerIcon"?: string;
        /**
          * The currently selected value
          * @default ''
         */
        "value": string;
        /**
          * Width variant
          * @default 'md'
         */
        "width": SelectWidth;
    }
    /**
     * @component ErixStatusBar
     * A Word-like status bar component positioned at the bottom of the editor.
     * Displays word/character count and theme toggle.
     */
    interface ErixStatusBar {
        /**
          * Character count
          * @default 0
         */
        "characterCount": number;
        /**
          * Current theme
          * @default 'light'
         */
        "theme": 'light' | 'dark' | string;
        /**
          * Word count
          * @default 0
         */
        "wordCount": number;
    }
    interface ErixTablePicker {
        /**
          * @default 8
         */
        "cols": number;
        /**
          * @default 8
         */
        "rows": number;
    }
    interface ErixTableToolbar {
        "update": () => Promise<void>;
        "view"?: EditorView;
    }
    /**
     * @component ErixToolbar
     * Dynamic toolbar that renders plugins based on configuration.
     * Only shows plugins that are configured - no static buttons.
     */
    interface ErixToolbar {
        /**
          * Toolbar items to display. Array of plugin IDs. Use '|' for separator (only shown between different groups). Example: ['bold', 'italic', '|', 'bullet-list', 'ordered-list']
          * @default []
         */
        "items": ToolbarItem[];
        /**
          * Show theme toggle in toolbar
          * @default true
         */
        "showThemeToggle": boolean;
        /**
          * Current theme
          * @default 'light'
         */
        "theme": 'light' | 'dark' | string;
        /**
          * Call this method from the parent to refresh the toolbar state
         */
        "updateActiveFormats": () => Promise<void>;
        /**
          * Reference to the ProseMirror EditorView
         */
        "view"?: EditorView;
    }
}
export interface ErixButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLErixButtonElement;
}
export interface ErixSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLErixSelectElement;
}
export interface ErixStatusBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLErixStatusBarElement;
}
export interface ErixTablePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLErixTablePickerElement;
}
export interface ErixToolbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLErixToolbarElement;
}
declare global {
    interface HTMLErixButtonElementEventMap {
        "erixClick": MouseEvent;
    }
    /**
     * @component ErixButton
     * A reusable button component for the editor toolbar and UI.
     */
    interface HTMLErixButtonElement extends Components.ErixButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLErixButtonElementEventMap>(type: K, listener: (this: HTMLErixButtonElement, ev: ErixButtonCustomEvent<HTMLErixButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLErixButtonElementEventMap>(type: K, listener: (this: HTMLErixButtonElement, ev: ErixButtonCustomEvent<HTMLErixButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLErixButtonElement: {
        prototype: HTMLErixButtonElement;
        new (): HTMLErixButtonElement;
    };
    /**
     * @component ErixDivider
     * A visual separator for toolbar groups and sections.
     */
    interface HTMLErixDividerElement extends Components.ErixDivider, HTMLStencilElement {
    }
    var HTMLErixDividerElement: {
        prototype: HTMLErixDividerElement;
        new (): HTMLErixDividerElement;
    };
    /**
     * @component ErixDropdown
     * A reusable dropdown component for the editor toolbar.
     * Provides a trigger button and a menu that opens on click.
     */
    interface HTMLErixDropdownElement extends Components.ErixDropdown, HTMLStencilElement {
    }
    var HTMLErixDropdownElement: {
        prototype: HTMLErixDropdownElement;
        new (): HTMLErixDropdownElement;
    };
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar and plugin system.
     */
    interface HTMLErixEditorElement extends Components.ErixEditor, HTMLStencilElement {
    }
    var HTMLErixEditorElement: {
        prototype: HTMLErixEditorElement;
        new (): HTMLErixEditorElement;
    };
    interface HTMLErixIconElement extends Components.ErixIcon, HTMLStencilElement {
    }
    var HTMLErixIconElement: {
        prototype: HTMLErixIconElement;
        new (): HTMLErixIconElement;
    };
    /**
     * @component ErixPopover
     * A smart popover component with auto-positioning.
     * Appends content to body for proper positioning.
     * Automatically flips position when there's not enough space.
     */
    interface HTMLErixPopoverElement extends Components.ErixPopover, HTMLStencilElement {
    }
    var HTMLErixPopoverElement: {
        prototype: HTMLErixPopoverElement;
        new (): HTMLErixPopoverElement;
    };
    interface HTMLErixSelectElementEventMap {
        "erixChange": string;
    }
    /**
     * @component ErixSelect
     * A reusable select/dropdown component for the editor toolbar.
     */
    interface HTMLErixSelectElement extends Components.ErixSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLErixSelectElementEventMap>(type: K, listener: (this: HTMLErixSelectElement, ev: ErixSelectCustomEvent<HTMLErixSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLErixSelectElementEventMap>(type: K, listener: (this: HTMLErixSelectElement, ev: ErixSelectCustomEvent<HTMLErixSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLErixSelectElement: {
        prototype: HTMLErixSelectElement;
        new (): HTMLErixSelectElement;
    };
    interface HTMLErixStatusBarElementEventMap {
        "themeToggle": void;
    }
    /**
     * @component ErixStatusBar
     * A Word-like status bar component positioned at the bottom of the editor.
     * Displays word/character count and theme toggle.
     */
    interface HTMLErixStatusBarElement extends Components.ErixStatusBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLErixStatusBarElementEventMap>(type: K, listener: (this: HTMLErixStatusBarElement, ev: ErixStatusBarCustomEvent<HTMLErixStatusBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLErixStatusBarElementEventMap>(type: K, listener: (this: HTMLErixStatusBarElement, ev: ErixStatusBarCustomEvent<HTMLErixStatusBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLErixStatusBarElement: {
        prototype: HTMLErixStatusBarElement;
        new (): HTMLErixStatusBarElement;
    };
    interface HTMLErixTablePickerElementEventMap {
        "selectGrid": { rows: number; cols: number };
    }
    interface HTMLErixTablePickerElement extends Components.ErixTablePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLErixTablePickerElementEventMap>(type: K, listener: (this: HTMLErixTablePickerElement, ev: ErixTablePickerCustomEvent<HTMLErixTablePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLErixTablePickerElementEventMap>(type: K, listener: (this: HTMLErixTablePickerElement, ev: ErixTablePickerCustomEvent<HTMLErixTablePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLErixTablePickerElement: {
        prototype: HTMLErixTablePickerElement;
        new (): HTMLErixTablePickerElement;
    };
    interface HTMLErixTableToolbarElement extends Components.ErixTableToolbar, HTMLStencilElement {
    }
    var HTMLErixTableToolbarElement: {
        prototype: HTMLErixTableToolbarElement;
        new (): HTMLErixTableToolbarElement;
    };
    interface HTMLErixToolbarElementEventMap {
        "themeToggle": void;
    }
    /**
     * @component ErixToolbar
     * Dynamic toolbar that renders plugins based on configuration.
     * Only shows plugins that are configured - no static buttons.
     */
    interface HTMLErixToolbarElement extends Components.ErixToolbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLErixToolbarElementEventMap>(type: K, listener: (this: HTMLErixToolbarElement, ev: ErixToolbarCustomEvent<HTMLErixToolbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLErixToolbarElementEventMap>(type: K, listener: (this: HTMLErixToolbarElement, ev: ErixToolbarCustomEvent<HTMLErixToolbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLErixToolbarElement: {
        prototype: HTMLErixToolbarElement;
        new (): HTMLErixToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "erix-button": HTMLErixButtonElement;
        "erix-divider": HTMLErixDividerElement;
        "erix-dropdown": HTMLErixDropdownElement;
        "erix-editor": HTMLErixEditorElement;
        "erix-icon": HTMLErixIconElement;
        "erix-popover": HTMLErixPopoverElement;
        "erix-select": HTMLErixSelectElement;
        "erix-status-bar": HTMLErixStatusBarElement;
        "erix-table-picker": HTMLErixTablePickerElement;
        "erix-table-toolbar": HTMLErixTableToolbarElement;
        "erix-toolbar": HTMLErixToolbarElement;
    }
}
declare namespace LocalJSX {
    /**
     * @component ErixButton
     * A reusable button component for the editor toolbar and UI.
     */
    interface ErixButton {
        /**
          * Whether the button is in an active/pressed state
          * @default false
         */
        "active"?: boolean;
        /**
          * Tooltip text for the button
          * @default ''
         */
        "buttonTitle"?: string;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onErixClick"?: (event: ErixButtonCustomEvent<MouseEvent>) => void;
        /**
          * The size of the button
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * The visual style variant of the button
          * @default 'default'
         */
        "variant"?: ButtonVariant;
    }
    /**
     * @component ErixDivider
     * A visual separator for toolbar groups and sections.
     */
    interface ErixDivider {
        /**
          * The orientation of the divider
          * @default 'vertical'
         */
        "orientation"?: DividerOrientation;
        /**
          * The size of the divider
          * @default 'md'
         */
        "size"?: DividerSize;
    }
    /**
     * @component ErixDropdown
     * A reusable dropdown component for the editor toolbar.
     * Provides a trigger button and a menu that opens on click.
     */
    interface ErixDropdown {
        /**
          * Whether to use extended menu style (for text-based options)
          * @default false
         */
        "extended"?: boolean;
        /**
          * Whether the dropdown menu is currently open
          * @default false
         */
        "open"?: boolean;
        /**
          * Position of the dropdown menu relative to the trigger
          * @default 'left'
         */
        "position"?: DropdownPosition;
        /**
          * Whether the trigger should show active state when open
          * @default true
         */
        "showActiveState"?: boolean;
        /**
          * Tooltip text for the trigger button
          * @default ''
         */
        "triggerTitle"?: string;
    }
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar and plugin system.
     */
    interface ErixEditor {
        "config"?: EditorConfig;
        "content"?: string;
        /**
          * @default 'Arial, sans-serif'
         */
        "defaultFontFamily"?: string;
        /**
          * @default '12pt'
         */
        "defaultFontSize"?: string;
        "disabledPlugins"?: string[];
        /**
          * @default 'Start typing...'
         */
        "placeholder"?: string;
        "plugins"?: ErixPluginConfig[];
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | string;
    }
    interface ErixIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size"?: number;
    }
    /**
     * @component ErixPopover
     * A smart popover component with auto-positioning.
     * Appends content to body for proper positioning.
     * Automatically flips position when there's not enough space.
     */
    interface ErixPopover {
        /**
          * Anchor element or bounding rect to position relative to
         */
        "anchorRect"?: DOMRect;
        /**
          * Whether to auto-flip when there's not enough space
          * @default true
         */
        "autoFlip"?: boolean;
        /**
          * Offset distance from the trigger (in pixels)
          * @default 8
         */
        "offset"?: number;
        /**
          * Whether the popover is visible
          * @default false
         */
        "open"?: boolean;
        /**
          * Preferred placement of the popover
          * @default 'top'
         */
        "placement"?: PopoverPlacement;
    }
    /**
     * @component ErixSelect
     * A reusable select/dropdown component for the editor toolbar.
     */
    interface ErixSelect {
        /**
          * Whether the select is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Icon-only mode - displays only an icon in the trigger (for compact toolbars)
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Emitted when the selection changes
         */
        "onErixChange"?: (event: ErixSelectCustomEvent<string>) => void;
        /**
          * Array of options for the select
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * Tooltip text for the select
          * @default ''
         */
        "selectTitle"?: string;
        /**
          * Icon name to display in the trigger (used with iconOnly mode)
         */
        "triggerIcon"?: string;
        /**
          * The currently selected value
          * @default ''
         */
        "value"?: string;
        /**
          * Width variant
          * @default 'md'
         */
        "width"?: SelectWidth;
    }
    /**
     * @component ErixStatusBar
     * A Word-like status bar component positioned at the bottom of the editor.
     * Displays word/character count and theme toggle.
     */
    interface ErixStatusBar {
        /**
          * Character count
          * @default 0
         */
        "characterCount"?: number;
        /**
          * Event emitted when theme toggle is requested
         */
        "onThemeToggle"?: (event: ErixStatusBarCustomEvent<void>) => void;
        /**
          * Current theme
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | string;
        /**
          * Word count
          * @default 0
         */
        "wordCount"?: number;
    }
    interface ErixTablePicker {
        /**
          * @default 8
         */
        "cols"?: number;
        "onSelectGrid"?: (event: ErixTablePickerCustomEvent<{ rows: number; cols: number }>) => void;
        /**
          * @default 8
         */
        "rows"?: number;
    }
    interface ErixTableToolbar {
        "view"?: EditorView;
    }
    /**
     * @component ErixToolbar
     * Dynamic toolbar that renders plugins based on configuration.
     * Only shows plugins that are configured - no static buttons.
     */
    interface ErixToolbar {
        /**
          * Toolbar items to display. Array of plugin IDs. Use '|' for separator (only shown between different groups). Example: ['bold', 'italic', '|', 'bullet-list', 'ordered-list']
          * @default []
         */
        "items"?: ToolbarItem[];
        /**
          * Event emitted when theme toggle is requested
         */
        "onThemeToggle"?: (event: ErixToolbarCustomEvent<void>) => void;
        /**
          * Show theme toggle in toolbar
          * @default true
         */
        "showThemeToggle"?: boolean;
        /**
          * Current theme
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | string;
        /**
          * Reference to the ProseMirror EditorView
         */
        "view"?: EditorView;
    }
    interface IntrinsicElements {
        "erix-button": ErixButton;
        "erix-divider": ErixDivider;
        "erix-dropdown": ErixDropdown;
        "erix-editor": ErixEditor;
        "erix-icon": ErixIcon;
        "erix-popover": ErixPopover;
        "erix-select": ErixSelect;
        "erix-status-bar": ErixStatusBar;
        "erix-table-picker": ErixTablePicker;
        "erix-table-toolbar": ErixTableToolbar;
        "erix-toolbar": ErixToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @component ErixButton
             * A reusable button component for the editor toolbar and UI.
             */
            "erix-button": LocalJSX.ErixButton & JSXBase.HTMLAttributes<HTMLErixButtonElement>;
            /**
             * @component ErixDivider
             * A visual separator for toolbar groups and sections.
             */
            "erix-divider": LocalJSX.ErixDivider & JSXBase.HTMLAttributes<HTMLErixDividerElement>;
            /**
             * @component ErixDropdown
             * A reusable dropdown component for the editor toolbar.
             * Provides a trigger button and a menu that opens on click.
             */
            "erix-dropdown": LocalJSX.ErixDropdown & JSXBase.HTMLAttributes<HTMLErixDropdownElement>;
            /**
             * @component ErixEditor
             * A rich text editor component with built-in toolbar and plugin system.
             */
            "erix-editor": LocalJSX.ErixEditor & JSXBase.HTMLAttributes<HTMLErixEditorElement>;
            "erix-icon": LocalJSX.ErixIcon & JSXBase.HTMLAttributes<HTMLErixIconElement>;
            /**
             * @component ErixPopover
             * A smart popover component with auto-positioning.
             * Appends content to body for proper positioning.
             * Automatically flips position when there's not enough space.
             */
            "erix-popover": LocalJSX.ErixPopover & JSXBase.HTMLAttributes<HTMLErixPopoverElement>;
            /**
             * @component ErixSelect
             * A reusable select/dropdown component for the editor toolbar.
             */
            "erix-select": LocalJSX.ErixSelect & JSXBase.HTMLAttributes<HTMLErixSelectElement>;
            /**
             * @component ErixStatusBar
             * A Word-like status bar component positioned at the bottom of the editor.
             * Displays word/character count and theme toggle.
             */
            "erix-status-bar": LocalJSX.ErixStatusBar & JSXBase.HTMLAttributes<HTMLErixStatusBarElement>;
            "erix-table-picker": LocalJSX.ErixTablePicker & JSXBase.HTMLAttributes<HTMLErixTablePickerElement>;
            "erix-table-toolbar": LocalJSX.ErixTableToolbar & JSXBase.HTMLAttributes<HTMLErixTableToolbarElement>;
            /**
             * @component ErixToolbar
             * Dynamic toolbar that renders plugins based on configuration.
             * Only shows plugins that are configured - no static buttons.
             */
            "erix-toolbar": LocalJSX.ErixToolbar & JSXBase.HTMLAttributes<HTMLErixToolbarElement>;
        }
    }
}
