/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName } from "./components/editor-icon/icons";
export { IconName } from "./components/editor-icon/icons";
export namespace Components {
    interface EditorIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size": number;
    }
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar.
     */
    interface ErixEditor {
        /**
          * Placeholder text when editor is empty.
          * @default 'Start typing...'
         */
        "placeholder": string;
        /**
          * The editor theme.
          * @default 'light'
         */
        "theme": 'light' | 'dark' | string;
    }
}
declare global {
    interface HTMLEditorIconElement extends Components.EditorIcon, HTMLStencilElement {
    }
    var HTMLEditorIconElement: {
        prototype: HTMLEditorIconElement;
        new (): HTMLEditorIconElement;
    };
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar.
     */
    interface HTMLErixEditorElement extends Components.ErixEditor, HTMLStencilElement {
    }
    var HTMLErixEditorElement: {
        prototype: HTMLErixEditorElement;
        new (): HTMLErixEditorElement;
    };
    interface HTMLElementTagNameMap {
        "editor-icon": HTMLEditorIconElement;
        "erix-editor": HTMLErixEditorElement;
    }
}
declare namespace LocalJSX {
    interface EditorIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size"?: number;
    }
    /**
     * @component ErixEditor
     * A rich text editor component with built-in toolbar.
     */
    interface ErixEditor {
        /**
          * Placeholder text when editor is empty.
          * @default 'Start typing...'
         */
        "placeholder"?: string;
        /**
          * The editor theme.
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | string;
    }
    interface IntrinsicElements {
        "editor-icon": EditorIcon;
        "erix-editor": ErixEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "editor-icon": LocalJSX.EditorIcon & JSXBase.HTMLAttributes<HTMLEditorIconElement>;
            /**
             * @component ErixEditor
             * A rich text editor component with built-in toolbar.
             */
            "erix-editor": LocalJSX.ErixEditor & JSXBase.HTMLAttributes<HTMLErixEditorElement>;
        }
    }
}
