/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName } from "./components/editor-icon/icons";
export { IconName } from "./components/editor-icon/icons";
export namespace Components {
    interface EditorIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size": number;
    }
    interface TypeForge {
        /**
          * The editor theme.
          * @default 'light'
         */
        "theme": 'light' | 'dark' | string;
    }
}
declare global {
    interface HTMLEditorIconElement extends Components.EditorIcon, HTMLStencilElement {
    }
    var HTMLEditorIconElement: {
        prototype: HTMLEditorIconElement;
        new (): HTMLEditorIconElement;
    };
    interface HTMLTypeForgeElement extends Components.TypeForge, HTMLStencilElement {
    }
    var HTMLTypeForgeElement: {
        prototype: HTMLTypeForgeElement;
        new (): HTMLTypeForgeElement;
    };
    interface HTMLElementTagNameMap {
        "editor-icon": HTMLEditorIconElement;
        "type-forge": HTMLTypeForgeElement;
    }
}
declare namespace LocalJSX {
    interface EditorIcon {
        /**
          * The name of the semantic editor icon.
         */
        "name": IconName;
        /**
          * The size of the icon in pixels (width and height).
          * @default 20
         */
        "size"?: number;
    }
    interface TypeForge {
        /**
          * The editor theme.
          * @default 'light'
         */
        "theme"?: 'light' | 'dark' | string;
    }
    interface IntrinsicElements {
        "editor-icon": EditorIcon;
        "type-forge": TypeForge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "editor-icon": LocalJSX.EditorIcon & JSXBase.HTMLAttributes<HTMLEditorIconElement>;
            "type-forge": LocalJSX.TypeForge & JSXBase.HTMLAttributes<HTMLTypeForgeElement>;
        }
    }
}
